/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real agent_1_solver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

int agent_1_solver_model_0_inner(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int agent_1_solver_model_0_inner_alloc_mem(void);
int agent_1_solver_model_0_inner_init_mem(int mem);
void agent_1_solver_model_0_inner_free_mem(int mem);
int agent_1_solver_model_0_inner_checkout(void);
void agent_1_solver_model_0_inner_release(int mem);
void agent_1_solver_model_0_inner_incref(void);
void agent_1_solver_model_0_inner_decref(void);
casadi_int agent_1_solver_model_0_inner_n_out(void);
casadi_int agent_1_solver_model_0_inner_n_in(void);
casadi_real agent_1_solver_model_0_inner_default_in(casadi_int i);
const char* agent_1_solver_model_0_inner_name_in(casadi_int i);
const char* agent_1_solver_model_0_inner_name_out(casadi_int i);
const casadi_int* agent_1_solver_model_0_inner_sparsity_in(casadi_int i);
const casadi_int* agent_1_solver_model_0_inner_sparsity_out(casadi_int i);
int agent_1_solver_model_0_inner_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int agent_1_solver_model_1_inner(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int agent_1_solver_model_1_inner_alloc_mem(void);
int agent_1_solver_model_1_inner_init_mem(int mem);
void agent_1_solver_model_1_inner_free_mem(int mem);
int agent_1_solver_model_1_inner_checkout(void);
void agent_1_solver_model_1_inner_release(int mem);
void agent_1_solver_model_1_inner_incref(void);
void agent_1_solver_model_1_inner_decref(void);
casadi_int agent_1_solver_model_1_inner_n_out(void);
casadi_int agent_1_solver_model_1_inner_n_in(void);
casadi_real agent_1_solver_model_1_inner_default_in(casadi_int i);
const char* agent_1_solver_model_1_inner_name_in(casadi_int i);
const char* agent_1_solver_model_1_inner_name_out(casadi_int i);
const casadi_int* agent_1_solver_model_1_inner_sparsity_in(casadi_int i);
const casadi_int* agent_1_solver_model_1_inner_sparsity_out(casadi_int i);
int agent_1_solver_model_1_inner_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
