% dynamic_solver - a fast solver generated by FORCES PRO v3.1.0
%
%   OUTPUT = dynamic_solver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.x0 - column vector of length 1200
%       PARAMS.xinit - column vector of length 9
%       PARAMS.all_parameters - column vector of length 1200
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.x001 - column vector of size 12
%       OUTPUT.x002 - column vector of size 12
%       OUTPUT.x003 - column vector of size 12
%       OUTPUT.x004 - column vector of size 12
%       OUTPUT.x005 - column vector of size 12
%       OUTPUT.x006 - column vector of size 12
%       OUTPUT.x007 - column vector of size 12
%       OUTPUT.x008 - column vector of size 12
%       OUTPUT.x009 - column vector of size 12
%       OUTPUT.x010 - column vector of size 12
%       OUTPUT.x011 - column vector of size 12
%       OUTPUT.x012 - column vector of size 12
%       OUTPUT.x013 - column vector of size 12
%       OUTPUT.x014 - column vector of size 12
%       OUTPUT.x015 - column vector of size 12
%       OUTPUT.x016 - column vector of size 12
%       OUTPUT.x017 - column vector of size 12
%       OUTPUT.x018 - column vector of size 12
%       OUTPUT.x019 - column vector of size 12
%       OUTPUT.x020 - column vector of size 12
%       OUTPUT.x021 - column vector of size 12
%       OUTPUT.x022 - column vector of size 12
%       OUTPUT.x023 - column vector of size 12
%       OUTPUT.x024 - column vector of size 12
%       OUTPUT.x025 - column vector of size 12
%       OUTPUT.x026 - column vector of size 12
%       OUTPUT.x027 - column vector of size 12
%       OUTPUT.x028 - column vector of size 12
%       OUTPUT.x029 - column vector of size 12
%       OUTPUT.x030 - column vector of size 12
%       OUTPUT.x031 - column vector of size 12
%       OUTPUT.x032 - column vector of size 12
%       OUTPUT.x033 - column vector of size 12
%       OUTPUT.x034 - column vector of size 12
%       OUTPUT.x035 - column vector of size 12
%       OUTPUT.x036 - column vector of size 12
%       OUTPUT.x037 - column vector of size 12
%       OUTPUT.x038 - column vector of size 12
%       OUTPUT.x039 - column vector of size 12
%       OUTPUT.x040 - column vector of size 12
%       OUTPUT.x041 - column vector of size 12
%       OUTPUT.x042 - column vector of size 12
%       OUTPUT.x043 - column vector of size 12
%       OUTPUT.x044 - column vector of size 12
%       OUTPUT.x045 - column vector of size 12
%       OUTPUT.x046 - column vector of size 12
%       OUTPUT.x047 - column vector of size 12
%       OUTPUT.x048 - column vector of size 12
%       OUTPUT.x049 - column vector of size 12
%       OUTPUT.x050 - column vector of size 12
%       OUTPUT.x051 - column vector of size 12
%       OUTPUT.x052 - column vector of size 12
%       OUTPUT.x053 - column vector of size 12
%       OUTPUT.x054 - column vector of size 12
%       OUTPUT.x055 - column vector of size 12
%       OUTPUT.x056 - column vector of size 12
%       OUTPUT.x057 - column vector of size 12
%       OUTPUT.x058 - column vector of size 12
%       OUTPUT.x059 - column vector of size 12
%       OUTPUT.x060 - column vector of size 12
%       OUTPUT.x061 - column vector of size 12
%       OUTPUT.x062 - column vector of size 12
%       OUTPUT.x063 - column vector of size 12
%       OUTPUT.x064 - column vector of size 12
%       OUTPUT.x065 - column vector of size 12
%       OUTPUT.x066 - column vector of size 12
%       OUTPUT.x067 - column vector of size 12
%       OUTPUT.x068 - column vector of size 12
%       OUTPUT.x069 - column vector of size 12
%       OUTPUT.x070 - column vector of size 12
%       OUTPUT.x071 - column vector of size 12
%       OUTPUT.x072 - column vector of size 12
%       OUTPUT.x073 - column vector of size 12
%       OUTPUT.x074 - column vector of size 12
%       OUTPUT.x075 - column vector of size 12
%       OUTPUT.x076 - column vector of size 12
%       OUTPUT.x077 - column vector of size 12
%       OUTPUT.x078 - column vector of size 12
%       OUTPUT.x079 - column vector of size 12
%       OUTPUT.x080 - column vector of size 12
%       OUTPUT.x081 - column vector of size 12
%       OUTPUT.x082 - column vector of size 12
%       OUTPUT.x083 - column vector of size 12
%       OUTPUT.x084 - column vector of size 12
%       OUTPUT.x085 - column vector of size 12
%       OUTPUT.x086 - column vector of size 12
%       OUTPUT.x087 - column vector of size 12
%       OUTPUT.x088 - column vector of size 12
%       OUTPUT.x089 - column vector of size 12
%       OUTPUT.x090 - column vector of size 12
%       OUTPUT.x091 - column vector of size 12
%       OUTPUT.x092 - column vector of size 12
%       OUTPUT.x093 - column vector of size 12
%       OUTPUT.x094 - column vector of size 12
%       OUTPUT.x095 - column vector of size 12
%       OUTPUT.x096 - column vector of size 12
%       OUTPUT.x097 - column vector of size 12
%       OUTPUT.x098 - column vector of size 12
%       OUTPUT.x099 - column vector of size 12
%       OUTPUT.x100 - column vector of size 12
%
%   [OUTPUT, EXITFLAG] = dynamic_solver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -6 - NaN or INF occured during evaluation of functions and derivatives. Please check your initial guess.
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = dynamic_solver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.rsnorm    - norm of stationarity condition
%       INFO.rcompnorm    - max of all complementarity violations
%       INFO.pobj      - primal objective
%       INFO.mu        - duality measure
%       INFO.solvetime - Time needed for solve (wall clock time)
%       INFO.fevalstime - Time needed for function evaluations (wall clock time)
%
% See also COPYING
