import numpy
import ctypes

name = "dynamic_solver"
requires_callback = True
lib = "lib/libdynamic_solver.so"
lib_static = "lib/libdynamic_solver.a"
c_header = "include/dynamic_solver.h"

# Parameter             | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
params = \
[("x0"                  , "dense" , ""               , ctypes.c_double, numpy.float64, (1200,   1), 1200),
 ("xinit"               , "dense" , ""               , ctypes.c_double, numpy.float64, (  9,   1),    9),
 ("all_parameters"      , "dense" , ""               , ctypes.c_double, numpy.float64, (1200,   1), 1200)]

# Output                | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
outputs = \
[("x001"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x002"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x003"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x004"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x005"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x006"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x007"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x008"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x009"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x010"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x011"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x012"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x013"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x014"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x015"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x016"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x017"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x018"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x019"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x020"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x021"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x022"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x023"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x024"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x025"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x026"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x027"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x028"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x029"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x030"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x031"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x032"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x033"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x034"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x035"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x036"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x037"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x038"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x039"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x040"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x041"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x042"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x043"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x044"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x045"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x046"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x047"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x048"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x049"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x050"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x051"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x052"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x053"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x054"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x055"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x056"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x057"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x058"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x059"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x060"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x061"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x062"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x063"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x064"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x065"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x066"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x067"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x068"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x069"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x070"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x071"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x072"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x073"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x074"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x075"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x076"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x077"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x078"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x079"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x080"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x081"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x082"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x083"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x084"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x085"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x086"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x087"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x088"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x089"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x090"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x091"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x092"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x093"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x094"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x095"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x096"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x097"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x098"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x099"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12),
 ("x100"                , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),   12)]

# Info Struct Fields
info = \
[('it', ctypes.c_int),
('it2opt', ctypes.c_int),
('res_eq', ctypes.c_double),
('res_ineq', ctypes.c_double),
('rsnorm', ctypes.c_double),
('rcompnorm', ctypes.c_double),
('pobj', ctypes.c_double),
('dobj', ctypes.c_double),
('dgap', ctypes.c_double),
('rdgap', ctypes.c_double),
('mu', ctypes.c_double),
('mu_aff', ctypes.c_double),
('sigma', ctypes.c_double),
('lsit_aff', ctypes.c_int),
('lsit_cc', ctypes.c_int),
('step_aff', ctypes.c_double),
('step_cc', ctypes.c_double),
('solvetime', ctypes.c_double),
('fevalstime', ctypes.c_double)
]