/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f110_kinematic_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[27] = {7, 3, 0, 7, 14, 21, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* f110_kinematic_model_expl_vde_forw:(i0[7],i1[7x7],i2[7x3],i3[3],i4[12])->(o0[7],o1[7x7],o2[7x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a4=(a0*a3);
  if (res[0]!=0) res[0][1]=a4;
  a4=6.3000000000000000e-02;
  a4=(a0/a4);
  a5=arg[0]? arg[0][6] : 0;
  a6=tan(a5);
  a7=(a4*a6);
  if (res[0]!=0) res[0][2]=a7;
  a7=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][3]=a7;
  a7=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][5]=a7;
  a7=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][6]=a7;
  a7=arg[1]? arg[1][3] : 0;
  a8=(a2*a7);
  a9=sin(a1);
  a10=arg[1]? arg[1][2] : 0;
  a11=(a9*a10);
  a11=(a0*a11);
  a8=(a8-a11);
  if (res[1]!=0) res[1][0]=a8;
  a8=(a3*a7);
  a11=cos(a1);
  a10=(a11*a10);
  a10=(a0*a10);
  a8=(a8+a10);
  if (res[1]!=0) res[1][1]=a8;
  a8=1.5873015873015873e+01;
  a7=(a8*a7);
  a7=(a6*a7);
  a10=arg[1]? arg[1][6] : 0;
  a12=cos(a5);
  a12=casadi_sq(a12);
  a10=(a10/a12);
  a10=(a4*a10);
  a7=(a7+a10);
  if (res[1]!=0) res[1][2]=a7;
  a7=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][3]=a7;
  a7=0.;
  if (res[1]!=0) res[1][4]=a7;
  if (res[1]!=0) res[1][5]=a7;
  if (res[1]!=0) res[1][6]=a7;
  a10=arg[1]? arg[1][10] : 0;
  a13=(a2*a10);
  a14=arg[1]? arg[1][9] : 0;
  a15=(a9*a14);
  a15=(a0*a15);
  a13=(a13-a15);
  if (res[1]!=0) res[1][7]=a13;
  a13=(a3*a10);
  a14=(a11*a14);
  a14=(a0*a14);
  a13=(a13+a14);
  if (res[1]!=0) res[1][8]=a13;
  a10=(a8*a10);
  a10=(a6*a10);
  a13=arg[1]? arg[1][13] : 0;
  a13=(a13/a12);
  a13=(a4*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][9]=a10;
  a10=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][10]=a10;
  if (res[1]!=0) res[1][11]=a7;
  if (res[1]!=0) res[1][12]=a7;
  if (res[1]!=0) res[1][13]=a7;
  a10=arg[1]? arg[1][17] : 0;
  a13=(a2*a10);
  a14=arg[1]? arg[1][16] : 0;
  a15=(a9*a14);
  a15=(a0*a15);
  a13=(a13-a15);
  if (res[1]!=0) res[1][14]=a13;
  a13=(a3*a10);
  a14=(a11*a14);
  a14=(a0*a14);
  a13=(a13+a14);
  if (res[1]!=0) res[1][15]=a13;
  a10=(a8*a10);
  a10=(a6*a10);
  a13=arg[1]? arg[1][20] : 0;
  a13=(a13/a12);
  a13=(a4*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][16]=a10;
  a10=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][17]=a10;
  if (res[1]!=0) res[1][18]=a7;
  if (res[1]!=0) res[1][19]=a7;
  if (res[1]!=0) res[1][20]=a7;
  a10=arg[1]? arg[1][24] : 0;
  a13=(a2*a10);
  a14=arg[1]? arg[1][23] : 0;
  a15=(a9*a14);
  a15=(a0*a15);
  a13=(a13-a15);
  if (res[1]!=0) res[1][21]=a13;
  a13=(a3*a10);
  a14=(a11*a14);
  a14=(a0*a14);
  a13=(a13+a14);
  if (res[1]!=0) res[1][22]=a13;
  a10=(a8*a10);
  a10=(a6*a10);
  a13=arg[1]? arg[1][27] : 0;
  a13=(a13/a12);
  a13=(a4*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][23]=a10;
  a10=arg[1]? arg[1][26] : 0;
  if (res[1]!=0) res[1][24]=a10;
  if (res[1]!=0) res[1][25]=a7;
  if (res[1]!=0) res[1][26]=a7;
  if (res[1]!=0) res[1][27]=a7;
  a10=arg[1]? arg[1][31] : 0;
  a13=(a2*a10);
  a14=arg[1]? arg[1][30] : 0;
  a15=(a9*a14);
  a15=(a0*a15);
  a13=(a13-a15);
  if (res[1]!=0) res[1][28]=a13;
  a13=(a3*a10);
  a14=(a11*a14);
  a14=(a0*a14);
  a13=(a13+a14);
  if (res[1]!=0) res[1][29]=a13;
  a10=(a8*a10);
  a10=(a6*a10);
  a13=arg[1]? arg[1][34] : 0;
  a13=(a13/a12);
  a13=(a4*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][30]=a10;
  a10=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][31]=a10;
  if (res[1]!=0) res[1][32]=a7;
  if (res[1]!=0) res[1][33]=a7;
  if (res[1]!=0) res[1][34]=a7;
  a10=arg[1]? arg[1][38] : 0;
  a13=(a2*a10);
  a14=arg[1]? arg[1][37] : 0;
  a15=(a9*a14);
  a15=(a0*a15);
  a13=(a13-a15);
  if (res[1]!=0) res[1][35]=a13;
  a13=(a3*a10);
  a14=(a11*a14);
  a14=(a0*a14);
  a13=(a13+a14);
  if (res[1]!=0) res[1][36]=a13;
  a10=(a8*a10);
  a10=(a6*a10);
  a13=arg[1]? arg[1][41] : 0;
  a13=(a13/a12);
  a13=(a4*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][37]=a10;
  a10=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][38]=a10;
  if (res[1]!=0) res[1][39]=a7;
  if (res[1]!=0) res[1][40]=a7;
  if (res[1]!=0) res[1][41]=a7;
  a10=arg[1]? arg[1][45] : 0;
  a13=(a2*a10);
  a14=arg[1]? arg[1][44] : 0;
  a9=(a9*a14);
  a9=(a0*a9);
  a13=(a13-a9);
  if (res[1]!=0) res[1][42]=a13;
  a13=(a3*a10);
  a11=(a11*a14);
  a11=(a0*a11);
  a13=(a13+a11);
  if (res[1]!=0) res[1][43]=a13;
  a10=(a8*a10);
  a10=(a6*a10);
  a13=arg[1]? arg[1][48] : 0;
  a13=(a13/a12);
  a13=(a4*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][44]=a10;
  a10=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][45]=a10;
  if (res[1]!=0) res[1][46]=a7;
  if (res[1]!=0) res[1][47]=a7;
  if (res[1]!=0) res[1][48]=a7;
  a10=arg[2]? arg[2][3] : 0;
  a13=(a2*a10);
  a12=sin(a1);
  a11=arg[2]? arg[2][2] : 0;
  a14=(a12*a11);
  a14=(a0*a14);
  a13=(a13-a14);
  if (res[2]!=0) res[2][0]=a13;
  a13=(a3*a10);
  a1=cos(a1);
  a11=(a1*a11);
  a11=(a0*a11);
  a13=(a13+a11);
  if (res[2]!=0) res[2][1]=a13;
  a10=(a8*a10);
  a10=(a6*a10);
  a13=arg[2]? arg[2][6] : 0;
  a5=cos(a5);
  a5=casadi_sq(a5);
  a13=(a13/a5);
  a13=(a4*a13);
  a10=(a10+a13);
  if (res[2]!=0) res[2][2]=a10;
  a10=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][3]=a10;
  if (res[2]!=0) res[2][4]=a7;
  a10=1.;
  if (res[2]!=0) res[2][5]=a10;
  if (res[2]!=0) res[2][6]=a7;
  a13=arg[2]? arg[2][10] : 0;
  a11=(a2*a13);
  a14=arg[2]? arg[2][9] : 0;
  a9=(a12*a14);
  a9=(a0*a9);
  a11=(a11-a9);
  if (res[2]!=0) res[2][7]=a11;
  a11=(a3*a13);
  a14=(a1*a14);
  a14=(a0*a14);
  a11=(a11+a14);
  if (res[2]!=0) res[2][8]=a11;
  a13=(a8*a13);
  a13=(a6*a13);
  a11=arg[2]? arg[2][13] : 0;
  a11=(a11/a5);
  a11=(a4*a11);
  a13=(a13+a11);
  if (res[2]!=0) res[2][9]=a13;
  a13=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][10]=a13;
  if (res[2]!=0) res[2][11]=a7;
  if (res[2]!=0) res[2][12]=a7;
  if (res[2]!=0) res[2][13]=a10;
  a13=arg[2]? arg[2][17] : 0;
  a2=(a2*a13);
  a11=arg[2]? arg[2][16] : 0;
  a12=(a12*a11);
  a12=(a0*a12);
  a2=(a2-a12);
  if (res[2]!=0) res[2][14]=a2;
  a3=(a3*a13);
  a1=(a1*a11);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[2]!=0) res[2][15]=a3;
  a8=(a8*a13);
  a6=(a6*a8);
  a8=arg[2]? arg[2][20] : 0;
  a8=(a8/a5);
  a4=(a4*a8);
  a6=(a6+a4);
  if (res[2]!=0) res[2][16]=a6;
  a6=arg[2]? arg[2][19] : 0;
  if (res[2]!=0) res[2][17]=a6;
  if (res[2]!=0) res[2][18]=a10;
  if (res[2]!=0) res[2][19]=a7;
  if (res[2]!=0) res[2][20]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int f110_kinematic_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f110_kinematic_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f110_kinematic_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f110_kinematic_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f110_kinematic_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f110_kinematic_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f110_kinematic_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void f110_kinematic_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f110_kinematic_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f110_kinematic_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f110_kinematic_model_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f110_kinematic_model_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f110_kinematic_model_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f110_kinematic_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f110_kinematic_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f110_kinematic_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
