/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f110_dynamic_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s3[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* f110_dynamic_model_expl_vde_adj:(i0[9],i1[9],i2[3],i3[13])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a5=(a3*a4);
  a2=(a2*a5);
  a5=sin(a1);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a6*a4);
  a5=(a5*a7);
  a2=(a2-a5);
  a5=cos(a1);
  a7=arg[1]? arg[1][0] : 0;
  a8=(a6*a7);
  a5=(a5*a8);
  a2=(a2-a5);
  a5=sin(a1);
  a8=(a3*a7);
  a5=(a5*a8);
  a2=(a2-a5);
  if (res[0]!=0) res[0][2]=a2;
  a2=5.0000000000000003e-02;
  a5=arg[0]? arg[0][5] : 0;
  a8=(a2*a5);
  a8=(a8+a6);
  a8=(a8/a3);
  a9=(a8/a3);
  a10=8.;
  a11=1.5000000000000000e+00;
  a12=arg[0]? arg[0][8] : 0;
  a13=atan(a8);
  a13=(a12-a13);
  a13=(a10*a13);
  a14=atan(a13);
  a14=(a11*a14);
  a15=cos(a14);
  a16=19.;
  a17=cos(a12);
  a18=1.6666666666666667e+00;
  a19=arg[1]? arg[1][5] : 0;
  a18=(a18*a19);
  a17=(a17*a18);
  a17=(a2*a17);
  a19=cos(a12);
  a20=5.0000000000000000e-01;
  a21=arg[1]? arg[1][4] : 0;
  a21=(a20*a21);
  a19=(a19*a21);
  a17=(a17+a19);
  a19=sin(a12);
  a22=arg[1]? arg[1][3] : 0;
  a20=(a20*a22);
  a19=(a19*a20);
  a17=(a17-a19);
  a17=(a16*a17);
  a15=(a15*a17);
  a15=(a11*a15);
  a17=1.;
  a13=casadi_sq(a13);
  a13=(a17+a13);
  a15=(a15/a13);
  a10=(a10*a15);
  a8=casadi_sq(a8);
  a8=(a17+a8);
  a8=(a10/a8);
  a9=(a9*a8);
  a15=2.;
  a13=(a5*a21);
  a13=(a15*a13);
  a19=(a2*a5);
  a19=(a19-a6);
  a19=(a19/a3);
  a22=(a19/a3);
  a23=12.;
  a24=atan(a19);
  a24=(a23*a24);
  a25=atan(a24);
  a25=(a11*a25);
  a25=cos(a25);
  a26=(a2*a18);
  a26=(a21-a26);
  a26=(a16*a26);
  a25=(a25*a26);
  a11=(a11*a25);
  a24=casadi_sq(a24);
  a24=(a17+a24);
  a11=(a11/a24);
  a23=(a23*a11);
  a19=casadi_sq(a19);
  a17=(a17+a19);
  a23=(a23/a17);
  a22=(a22*a23);
  a13=(a13+a22);
  a9=(a9-a13);
  a13=(a3+a3);
  a13=(a13*a20);
  a9=(a9-a13);
  a13=arg[0]? arg[0][7] : 0;
  a13=(a13*a20);
  a13=(a2*a13);
  a9=(a9-a13);
  a13=sin(a1);
  a13=(a13*a4);
  a9=(a9+a13);
  a13=cos(a1);
  a13=(a13*a7);
  a9=(a9+a13);
  if (res[0]!=0) res[0][3]=a9;
  a5=(a5*a20);
  a5=(a15*a5);
  a23=(a23/a3);
  a5=(a5-a23);
  a8=(a8/a3);
  a5=(a5-a8);
  a9=cos(a1);
  a9=(a9*a4);
  a5=(a5+a9);
  a1=sin(a1);
  a1=(a1*a7);
  a5=(a5-a1);
  if (res[0]!=0) res[0][4]=a5;
  a23=(a2*a23);
  a5=(a15*a3);
  a5=(a5*a21);
  a23=(a23-a5);
  a15=(a15*a6);
  a15=(a15*a20);
  a23=(a23+a15);
  a8=(a2*a8);
  a23=(a23-a8);
  a8=arg[1]? arg[1][2] : 0;
  a23=(a23+a8);
  if (res[0]!=0) res[0][5]=a23;
  if (res[0]!=0) res[0][6]=a0;
  a0=1.0000000000000001e-01;
  a3=(a2*a3);
  a0=(a0-a3);
  a0=(a0*a20);
  if (res[0]!=0) res[0][7]=a0;
  a0=sin(a12);
  a14=sin(a14);
  a16=(a16*a14);
  a2=(a2*a16);
  a2=(a2*a18);
  a0=(a0*a2);
  a2=sin(a12);
  a21=(a16*a21);
  a2=(a2*a21);
  a0=(a0+a2);
  a12=cos(a12);
  a16=(a16*a20);
  a12=(a12*a16);
  a0=(a0+a12);
  a10=(a10-a0);
  if (res[0]!=0) res[0][8]=a10;
  a10=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][9]=a10;
  a10=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][10]=a10;
  a10=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][11]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int f110_dynamic_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f110_dynamic_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f110_dynamic_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f110_dynamic_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f110_dynamic_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f110_dynamic_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f110_dynamic_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void f110_dynamic_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f110_dynamic_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f110_dynamic_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f110_dynamic_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f110_dynamic_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f110_dynamic_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f110_dynamic_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f110_dynamic_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f110_dynamic_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
